const CartActionTypes={
    TOGGLE_CART_HIDDEN:'TOGGLE_CART_HIDDEN',
    ADD_ITEM:'ADD_ITEM',
    DELETE_ITEM_IN_CHECKOUT:'DELETE_ITEM_IN_CHECKOUT',
    DELETE_ITEM_IN_CART:'DELETE_ITEM_IN_CART'
}

export default CartActionTypes;